version: "3.8"

services:
  backend:
    image: kaancaninc/sidebery-backend:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=production
    networks:
      - sidebery_net

  frontend:
    image: kaancaninc/sidebery-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - sidebery_net

networks:
  sidebery_net:
    name: sidebery_net
